# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# Find the sum of all the even-valued terms in the sequence which do not exceed four million.

val1 = 1
val2 = 2
max = 4000000
total = 2

while val2 < max:
	next = val1 + val2
	if next % 2 == 0:
		total += next
	val1 = val2
	val2 = next

print(total)
